examples/README.md, examples/bert/deepspeed_hf.py, examples/gpt/deepspeed_hf.py
The default micro-batch size at the beginning of the function leads to incorrect arguments passed into the DeepSpeed engine. This PR removes the default micro-batch size.
=> [Bugfix] Fix batch size in slapo-deepspeed

examples/albert/megatron_hf.py, examples/bert/megatron_hf.py, examples/gpt/megatron_hf.py, examples/opt/megatron_hf.py, examples/roberta/megatron_hf.py, examples/t5/megatron_hf.py
`import transformers` needs to be placed before `import megatron`, otherwise we will receive segfault for more recent transformers.
=> Fix transformers import order in megatron scripts

ci/task_lint.sh, slapo/initialization.py, slapo/model_dialect/deepspeed/pipeline.py, slapo/model_dialect/registry.py, slapo/pipeline.py, slapo/schedule.py, tests/test_pipeline_partition.py
This PR analyzes whether parameters are tie together by looking at their `nn.Paramter` object IDs. Accordingly, this analysis has to be done before the consolidation (if needed); otherwise all `nn.Parameter` objects will be replaced so that their object IDs won't be the same anymore.
Note that the above analysis works only when parameters are pointing to the same Python object. In other words, for the distributed training that requires weight consolidation, users have to explicitly call `tie_weights` one more time when initializing the model with empty weights. For example:
```python
with slapo.init_empty_weights():
model = get_model()
model.tie_weights()
sch = slapo.create_schedule(model, ...)
sch.build(...)
```
In addition, this PR also refactors the pipeline logic in `schedu.build`. …
=> [Pipeline] Tie weight analysis

benchmark/configs/single_node_v100_ckpt.cfg, docker/Dockerfile, examples/README.md, examples/utils.py, examples/wideresnet/deepspeed_hf.py, examples/wideresnet/megatron_hf.py, examples/wideresnet/model.py, slapo/schedule.py
This PR tries to reproduce the experimental results presented in the paper using the provided docker image. Most of the errors are dependency issues.
Following items list the failed test cases and the root causes:
=> [Bugfix] Reproduce experimental results in docker image

.github/workflows/ci_unit_test.yml, ci/install_test_pkgs.sh, ci/submit_job.py, ci/task_unit_test.sh, conftest.py, docker/push.sh, examples/gpt/model.py, examples/gpt/schedule.py, examples/opt/model.py, examples/opt/schedule.py, slapo/model_dialect/__init__.py, slapo/model_dialect/deepspeed/engine.py, slapo/model_dialect/deepspeed/pipeline.py, slapo/model_dialect/registry.py, slapo/pipeline.py, slapo/schedule.py, tests/test_pipeline_partition.py, tests/test_shard.py
When running pipeline on DeepSpeed MiCS (not open source yet), we need to call `model.register_tied_weights` to let the runtime sync tied weights. Accordingly, this PR leverages tie weight analysis and tie rank analysis to call the API.
Meanwhile, since we analyze tied weights by checking whether two or more weights are referring to the same nn.Parameter Python object, any operations that replace the nn.Parameter object will break this assumption. For example, `shard` and `replace`. While we leave `replace` as the future work, this PR deals with sharding as follows:
1. When `create_schedule`, we analyze tied weights and generate a dict `self.tie_weights = {param: param}`, where key and value are the same nn.Parameter.
2. When `shard` the parameter in `self.tie_weights`, we update the …
=> [Pipeline] Register tie weights

slapo/schedule.py, tests/test_trace.py
This PR updates the unit tests for tracer. Also, it adds a syntactic sugar for users to easily retrieve submodules in `nn.Sequential`. For example, previously, users can only use `sch["layer1"]["0"]["downsample"]` to access submodules in WideResNet. This PR enables the `sch["layer1.0.downsample"]` access.
=> [Test] Add tracer unit tests

examples/data_util.py, slapo/schedule.py
The DeepSpeed pipeline runtime doesn't support dynamic batch, meaning that the last batch may cause hanging. This PR drops the last batch to workaround this issue.
cc @szhengac @zarzen
=> [Pipeline] Drop last batch in DeepSpeed scripts

examples/gpt/deepspeed_hf.py, examples/gpt/model.py, examples/gpt/schedule.py, examples/opt/schedule.py, examples/wideresnet/schedule.py, slapo/schedule.py, slapo/sharding/__init__.py, slapo/sharding/utils.py, tests/end2end.py, tests/test_shard.py
This PR revises the sequence parallelism for GPT model and makes it optional. We add `tensor_parallel_output_grad` to indicate if the following operator after all-gather is sharded. If yes, we need to perform reduce-scatter during the backward and whereas a split is only needed for the following duplicate computation. 
For GPT model, we will first add sequence partition after embedding lookup and another all-gather after the final layer-norm because of `hidden_states = hidden_states.view(output_shape)` before returning it:
```
if sequence_parallel:
sch[word_embed_name].sync(mode="fwd_post", sync_op_or_fn="scatter", axis=1)
sch[pos_embed_name].sync(mode="fwd_post", sync_op_or_fn="scatter", axis=1)
sch[final_ln_name].sync(
mode="fwd_post",
sync_op_or_fn="all_gather",
axis=1, …
```
=> [Bugfix] Fix sequence parallelism

scripts/lint/pylintrc, slapo/pipeline.py, slapo/schedule.py, slapo/utils/common.py, tests/test_replace.py
The current `.trace` did the following two steps:
1. trace the target module to be a GraphModule.
2. replace the original module with the new GraphModule.
However, the traced GraphModule won't include any hooks in the original module, so the `.sync` primitives specified before tracing, including `.trace` and `.trace_for_pipeline` are dropped. This PR fixes this issue by transferring all hooks from the original module to the new one. For example, a hook registered to broadcast inputs will be transferred 2 times during scheduling:
1. After tracing the top module, the hook is transferred from the original module to the traced module.
2. After wrapping pipeline stage to partitioned modules, the (pre-forward) hook is transferred from the original module to the first pipeline stage module …
=> [Schedule][replace] Transfer hooks when replacing modules

slapo/pipeline.py, slapo/utils/common.py
Fix #27 that transfers the hooks to the wrong module.
cc @szhengac
=> [Bugfix] Transfer hooks in pipeline modules

slapo/schedule.py, slapo/tracer.py, tests/test_trace.py
This PR adds `flatten` argument to the `.trace()` primitive, so users can determine whether they want the traced graph to be flattened or not. Combining with `leaf_module`, users can have fine-grained control on how many and which levels of submodules they want to be flattened or hierarchical. For example, to only flatten the `BertAttention` layer but not the inner `BertSelfAttention` and `BertSelfOutput` modules, users can write the following code.
```python
input_names = ["hidden_states", "attention_mask"]
sig = inspect.signature(sub_sch.mod.forward)
concrete_args = {
p.name: p.default for p in sig.parameters.values() if p.name not in input_names
}
sub_sch.trace(
tracer="pytorch",
flatten=True,
concrete_args=concrete_args,
leaf_modules=["BertSelfAttention", "BertSelfOutput"],
)
```
As …
=> [Tracer] Add `flatten` argument to .trace()

benchmark/bench_single_node.py, examples/albert/deepspeed_hf.py, examples/bert/deepspeed_hf.py, examples/gpt/deepspeed_hf.py, examples/opt/deepspeed_hf.py, examples/roberta/deepspeed_hf.py, examples/t5/deepspeed_hf.py, examples/utils.py, examples/wideresnet/deepspeed_hf.py, examples/wideresnet/megatron_hf.py, slapo/model_dialect/deepspeed/utils.py, slapo/model_dialect/megatron/utils.py, tests/end2end.py
Fix the benchmark utility `train_with_torch` to consider micro batch when printing the log. Now it accepts optional `micro_batch_size` and only prints the loss per global batch.
cc @zarzen
=> [Benchmark] Fix ZeRO-3 step log

examples/albert/deepspeed_hf.py, examples/bert/deepspeed_hf.py, examples/gpt/deepspeed_hf.py, examples/gpt/schedule.py, examples/opt/deepspeed_hf.py, examples/roberta/deepspeed_hf.py, examples/t5/deepspeed_hf.py, examples/utils.py, examples/wideresnet/deepspeed_hf.py, slapo/model_dialect/deepspeed/engine.py
- When TP is enabled and PP is disabled, the last linear layer is sharded. Thus, we need `ParallelCrossEntropy` as the loss instead of the loss from HF. 
- Using TP with ZeRO-1 optimizer in DS runtime requires `mpu` as input to the `deespeed.initialize(...)` function. 
- When `--disable_pipeline` is used for disabling pipeline parallelism, we need to get the `num_mp` parameters from the `args`. 
- With the fix, the loss converge to about 7.x after 200 steps, which is still slower than ZeRO-1 or ZeRO-3 only. 
- For now only tested with GPT model.
=> [Bugfix] Fix for sharding TP only

slapo/model_dialect/deepspeed/engine.py
- Check the pipeline parallel size before creating the `mpu` grid to avoid initialization error 
- Avoid creating duplicate communication groups when pipeline parallelism is used.
=> [Bugfix] Using None for mpu when PP > 1

examples/albert/schedule.py, examples/bert/schedule.py, examples/gpt/schedule.py, examples/opt/model.py, examples/opt/schedule.py, examples/roberta/schedule.py, examples/t5/schedule.py, slapo/op/linear.py, slapo/pattern.py, slapo/schedule.py, slapo/utils/mapping.py, tests/test_fusion.py, tests/test_subgraph.py
This PR adds a new primitive called `.fuse(subgraph, compiler)` for operator fusion. Currently we only support pattern-based [vertical operator fusion](https://sisyphus.gitbook.io/project/deep-learning-basics/computation-graph-optimization/tensorrt-computation-graph-optimization) using TorchScript as the backend compiler. A simple example is shown below.
```python
class Model(nn.Module):
def __init__(self):
super().__init__()
self.conv = nn.Conv2d(3, 32, 3)
def forward(self, x):
x = self.conv(x)
x = F.relu(x)
x = x + 1
return x
mod = Model()
sch = slapo.create_schedule(mod)
def pattern(x: torch.Tensor):
x = F.relu(x)
x = x + 1
return x
subgraph = sch.find(pattern)
sch.fuse(subgraph, compiler="TorchScript", name="FusedReLU")
```
The fusion performance needs to be tested. As I first create …
=> [Schedule] Add .fuse() primitive

ci/task_unit_test.sh, conftest.py, examples/gpt/deepspeed_hf.py, examples/gpt/megatron_hf.py, examples/gpt/model.py, examples/gpt/schedule.py, slapo/__init__.py, slapo/checkpoint.py, slapo/op/__init__.py, slapo/op/dropout.py, slapo/random.py, slapo/schedule.py, tests/test_checkpoint.py, tests/test_op.py, tests/test_random.py, tests/test_shard.py, tests/test_shard_sync_op.py
- Add random state management to deal with the requirements of using the same or different random seeds in a TP group. The implementation is based on the one in Megatron-LM.
- Add an activation checkpointing with the consideration of random states.
- Add an op `DropoutWithTensorParallel` that can be replaced by users when writing a schedule.
- Add unit tests.
- Disable randomly plugin in pytest. This plugin makes our random seed setup in the test fixture useless.
Notes:
1. We now offer an API `set_random_seed` for users to call in the training script. Users have to manually call it and specify the rank of 3D parallelism.
2. All changes in this PR will have no impact if `set_random_seed` is not called in advance.
3. Fidelity testing shows the updated GPT schedule with 3D parallelism could …
=> [Random] Random state management

ci/task_unit_test.sh, docker/Dockerfile, examples/README.md, examples/bert/schedule.py, examples/data_util.py, examples/gpt/deepspeed_hf.py, examples/gpt/model.py, examples/gpt/schedule.py, examples/opt/schedule.py, examples/roberta/schedule.py, scripts/xformers_patch, slapo/utils/report.py
**To existing developers:** please update your environments by referring to examples/README.md or Dockerfile. 
This PR updates `epoi` used in GPT schedule to the latest version, which uses flash-attention triton kernel for better performance and attention dropout supports. The GPT schedule is also updated to support different random seeds within a TP group for attention dropout. With this PR, Slapo 3D could align the loss value of ZeRO-3 even with dropout enabled.
1. **Update GPT schedule dependency.** `epoi`, `xformers` are updated to the latest compatible commits. Introduce `flash_attention` as the new dependency of GPT scheduling.
2. The latest `xformers` doesn't allow CUTLASS kernel to take bias. We use a patch to fix it temporary.
3. **Dockerfile.** The docker file is updated. The CI …
=> [GPT] Use flash-attention and enable dropout

ci/task_unit_test.sh, docker/Dockerfile, examples/README.md, examples/gpt/model.py, examples/gpt/schedule.py, slapo/op/__init__.py, slapo/op/attention.py, slapo/op/bias_gelu.py, slapo/op/mlp.py, slapo/utils/common.py, tests/test_op.py
This is a prerequisite PR for adding HF GPT-2 schedule.
- Implement attention ops that use flash-attention and xformrs.
- Implement bias_gelu ops that use torchscript or torch compiler.
- Change the GPT-Neo schedule to use these ops, so that now GPT-Neo schedule doesn't depend on `epoi` anymore. Later we will update the schedules of other example models accordingly.
- [Test] Add `-rxXs` to let pytest print reasons of skipped tests.
- [Docker] Update flash-attention commit hash which improves the kernel performance by ~12%. CI image is not updated because this change doesn't impact the functionality.
@szhengac @chhzh123
=> [Op] Add attention and bias_gelu ops

slapo/schedule.py, slapo/tracer.py
This PR fixes #13 and #30 by removing the legacy code of renaming self attention module for HuggingFace models. As now we only trace the module when needed and also replace the attention module with our own module, the naming issue probably may not be a problem. We also do not refer to `self_m` in our example schedules, so I remove the renaming part from the tracer, and only prompt a warning when the tracer meets those `self` modules.
cc @szhengac @comaniac
=> [Tracer] Remove SelfAttention renaming

examples/gpt/deepspeed_hf.py, examples/gpt/schedule.py, examples/gpt2/deepspeed_hf.py, examples/gpt2/model.py, examples/gpt2/schedule.py, slapo/op/attention.py, tests/test_op.py
Add an example of HuggingFace GPT-2. Later we should rename `examples/gpt` to `examples/gpt-neo` to reduce the confusion.
Example benchmark commands:
```
deepspeed ./examples/gpt2/deepspeed_hf.py --pmp 2 --tmp 2 --batch_size 32 --micro_batch_size 4 --model_name gpt2-xl --iter_nums 170 --hidden-size 2048 --nlayers 24 --num-attn-heads 16 --dropout 0.1 --activation_function gelu --seq_len 2048
```
cc @szhengac
=> [Model] Add HuggingFace GPT-2

examples/gpt/deepspeed_hf.py, examples/gpt/model.py, examples/gpt/schedule.py, examples/gpt2/model.py, examples/gpt2/schedule.py, slapo/op/attention.py, tests/test_op.py
Pointed out by @szhengac, the current logic that uses `.chunk(3, dim=-1)` to split qkv assumes different data layouts for TP=1 and TP>1 cases. Specifically, when TP=1, we assume the qkv is contiguous, meaning that the weight layout is `[q0q1,...,k0k1, ..., v0v1]`. However, when TP>1, since weight is sharded along axis=0, each partitioned weight has `[3 * H // TP]`. This assumes the qkv layout is interleaved (i.e., `[q0k0v0, ...]`).
This won't be an issue if we always run the model within the same case, but the produces incorrect results if, for example, we trained the model with TP=2 but now want to fine-tune it with TP=1. Although transposing trained weights could also resolve this issue, this seems not straightforward to users.
This PR fixes this issue by assuming the qkv weights are …
=> [Op] Refactor qkv processing

examples/data_util.py, examples/gpt/deepspeed_hf.py, examples/gpt/megatron_hf.py, examples/gpt/model.py, examples/gpt/schedule.py, examples/gpt2/deepspeed_hf.py, examples/gpt2/model.py, examples/gpt2/schedule.py
The current GPT dataloader does not use prefetching. This PR fixes that by adding num_workers=2 and removes cuda in collate_fn, which will reinitialize cuda context in subprocesses.
=> Add num_workers to GPT dataloader

examples/gpt/deepspeed_hf.py, examples/gpt/megatron_hf.py, examples/gpt/model.py, examples/gpt/schedule.py, examples/gpt2/deepspeed_hf.py, examples/gpt2/model.py, examples/gpt2/schedule.py, examples/utils.py, slapo/op/attention.py, tests/test_op.py
It achieves better latency over the triton one in the case of no attention mask, which are ignored in both CUDA and triton kernels for now.
=> [Op] Add flash-attention CUDA kernel

slapo/sharding/sync_ops.py
Create tensor on cpu and then transfer it to GPU is slow. This pr fixes it by creating tensor on target device.
=> [Bugfix] Fix tensor device

slapo/utils/report.py, tests/test_consolidation.py
This PR adds a test of initialization to make sure the `init_weight` bypass works in `slapo.build`. Also, GPU memory usage is measured to ensure `init_empty_weights` does not introduce extra memory overheads.
=> [Test] Add default initialization test

examples/bert/schedule.py, examples/gpt/schedule.py, examples/gpt2/schedule.py, examples/opt/schedule.py, examples/roberta/schedule.py, slapo/schedule.py, slapo/utils/common.py, tests/test_replace.py
This PR creates subschedule for replaced subgraph module (vertical & horizontal fusion) and attach hooks to the new module. Previously, we only create subschedule for single module replacement. Also, the `replace_function` API is changed, accepting a tuple `(str, fx.Node)` instead of a single node, in order to match the API of `replace_module`. Corresponding tests are also added to ensure correctness.
=> [Schedule] Create subschedule for subgraph replacement

README.md, slapo/schedule.py, tests/test_checkpoint.py
This PR adds support to partial checkpointing, i.e., only checkpoint a subgraph. Users can use `.find()` primitive to obtain the required subgraph and then pass it to `.checkpoint()` primitive. A new checkpointed module will be attached to the original parent module.
=> [Schedule] Support partial checkpointing

examples/gpt2/deepspeed_hf.py, slapo/framework_dialect/deepspeed/engine.py
For experimental purpose, this PR supports the case that TP=#GPUs. Specifically,
1) After scheduling the model, set `enable_pipeline=False` so that we will use DeepSpeed engine with ZeRO-0 instead of the pipeline engine.
2) In DeepSpeed dialect, we make sure the mpu with device topology is passed to DeepSpeed engine even when pipeline is disabled, so that DeepSpeed runtime can correctly configure data parallel groups.
cc @zarzen
=> [DeepSpeed] Support TP=nGPU and PP=DP=1

slapo/schedule.py, tests/test_replace.py, tests/test_subgraph.py
For the following tree-like subgraph with multiple inputs, if we use the `pattern` to match the `+`, `-`, and `*` operators, only `+` and `*` will be returned. This is because the current implementation of subgraph matching starts from the first instruction of the original subgraph and target subgraph, and test if **users** of the instruction are the same. The process is iterative and basically is a DFS. However, this process may ignore instruction `b` since `b` is not the user of `a`.
```python
class Model(nn.Module):
def forward(self, x, y, z):
a = x + y
b = y - z
c = a * b
return c
```
```python
def pattern(x, y, z):
return (x + y) * (y - z)
```
To solve this problem, we can simply traverse the graph node from top to bottom following the order of the link list (i.e., visiting the …
=> [Bugfix] Support tree-like subgraph matching

slapo/schedule.py
Previously we use `sch.metadata.base_params` to maintain the original parameter shape before sharding. However, the scope of schedule metadata is limited to the current schedule and won't be transferred if `.replace` is used, so `sch.metadata.base_params` won't be correct anymore in this case.
In this PR, we removed `sch.metadata.base_params` and directly set an attribute to sharded parameters to record their original shapes. In future, we should revisit the `sch.metadata` design.
cc @szhengac @chhzh123
=> [Bugfix] Consolidate params with orig size

examples/gpt2/deepspeed_hf.py, examples/gpt_neo/deepspeed_hf.py, examples/utils.py, slapo/model_schedule/gpt2.py, slapo/model_schedule/gpt_neo.py, slapo/schedule.py
Add tag to layernorm when sequence parallelism is enabled. This will trigger additional allreduce within tensor parallel group in deepspeed.
=> [Feature] Layernorm Tag

examples/gpt2/deepspeed_hf.py, examples/utils.py
`torchrun` does not inject the `local_rank` via command arguement `--local_rank`. Instead reading from the environment variable `LOCAL_RANK`. 
The modification allows following launch command, which does not require a `hostfile`. 
```
torchrun --master_port $MASTER_PORT \
--master_addr $JOB_NAME-master-0 \
--nnodes $WORLD_SIZE \
--nproc_per_node 8 \
--node_rank $RANK \
/mnt/zhzhn/slapo/examples/gpt2/deepspeed_hf.py \
--tmp 4 --pmp 2 --hidden-size 2048 --nlayers 12 \
--num-attn-heads 16 
```
=> Enable launch training with torchrun

README.md, slapo/__init__.py, slapo/build.py, slapo/op/__init__.py, slapo/pipeline.py, slapo/primitives/__init__.py, slapo/primitives/base.py, slapo/primitives/checkpoint.py, slapo/primitives/fusion.py, slapo/primitives/pipeline.py, slapo/primitives/replace.py, slapo/primitives/tensor_parallel.py, slapo/schedule.py, slapo/sharding/__init__.py, slapo/sharding/shard_ops.py
This PR refactors the schedule primitives to make them more systematic and extensible:
* Now all primitives derived the base class `Primitive` that defines the required APIs (`name`, `apply`, and optional `init_metadata`).
* The `apply` function takes the schedule as the first argument, followed by any primitive specific arguments.
* The `init_metadata` allows each primitive to register their metadata, so the original schedule metadata only defines tie_weights metadata now. Meanwhile, we currently also put some metadata, such as the original shape before sharding, directly to nn.Parameter. I'll send a follow-up PR to better organize them.
* All primitives are registered and maintained in a table, and they will be dynamically set to a schedule when it is constructed. In other words, users …
=> [Refactor] Schedule primitives

README.md, slapo/build.py, slapo/framework_dialect/deepspeed/pipeline.py, slapo/model_schedule/albert.py, slapo/model_schedule/bert.py, slapo/model_schedule/gpt2.py, slapo/model_schedule/gpt_neo.py, slapo/model_schedule/opt.py, slapo/model_schedule/t5.py, slapo/model_schedule/wideresnet.py, slapo/primitives/annotate.py, slapo/primitives/pipeline.py, slapo/primitives/tensor_parallel.py, slapo/schedule.py, slapo/utils/common.py, tests/test_annotate.py, tests/test_op.py
This PR introduces a new primitive `.annotate()` that sets an attribute to the assigned parameter. There are mainly two use cases:
1. When sharding, we record the original shape for model consolidation.
2. Runtime such as DeepSpeed pipeline may apply certain processes based on attributes (e.g., `tensor_model_parallel` or `replicated_param`).
The annotated attribute names will be maintained in the schedule metadata of the top module. The top module schedule will not be replaced, so the metadata is guaranteed to be propagated to the model building phase. To maintain the annotations, a utility `transfer_param_tags` is also introduced.
In addition, this PR also rename `.trace_for_pipeline()` to `.trace_until()`, because this API is not only for pipelining but could also be used for other …
=> [Primitive] .annotate() and .trace_until()

.github/workflows/ci_lint.yml, .github/workflows/sphinx_build.yml
This PR updates the CI configuration file to make the documentation build only when the files in the `docs` folder are changed. Also, it changes the checkout branch to the current one instead of the `docs` branch (which is no longer maintained since it has been merged to the main branch).
=> [CI] Update CI rules for docs

examples/gpt2/deepspeed_hf.py, examples/gpt_neo/deepspeed_hf.py, slapo/model_schedule/gpt2.py, slapo/model_schedule/gpt_neo.py, slapo/model_schedule/opt.py, slapo/op/__init__.py, slapo/op/fused_bias.py, slapo/op/linear.py, slapo/op/mlp.py, slapo/random.py, tests/test_op.py, tests/test_random.py
1. Fuse bias and dropout in op.FusedMLP.
2. Add unit tests for op.FusedMLP.
3. Correct random states in GPT schedules when sequence parallelism is enabled.
cc @chhzh123 @szhengac
=> [Op] Fuse bias+dropout in FusedMLP

slapo/model_schedule/gpt2.py, slapo/model_schedule/gpt_neo.py, slapo/op/__init__.py, slapo/op/linear.py, slapo/primitives/tensor_parallel.py, slapo/sharding/shard_ops.py, tests/test_fusion.py, tests/test_op.py, tests/test_shard.py, tests/utils.py
Close #10 
This PR refactors shard ops by modulizing necessary methods. In this way, we could easily customize the behavior of sharding a certain op/module. Accordingly, we also ported PR #23 as a demonstration.
Detail changes:
1. A new op `LinearWithSyncFunc`.
2. An API "register_shard_method" that allows each module to register a set of sharding related methods.
3. Two APIs "apply_shard_method" and "apply_sync_method" dispatches to the right method based on the module type.
4. Customize the sharding of nn.Linear and Conv1D.
5. To fix #10, in addition to performing sync op before bias addition, we also have to perform an additional allreduce on the bias gradient. Now this is achieved by annotating the bias parameters, just like layer norm.
cc @szhengac @chhzh123
=> [Refactor] Modulize sharding methods

slapo/op/linear.py, slapo/primitives/checkpoint.py, slapo/primitives/tensor_parallel.py, slapo/tracer.py
This PR changes the way of implementing `.fork_rng()`. Now it replaces the forward function instead of an entire module. However, this approach results in incorrect trace results. Specifically, this module can still be traced, but the traced graph is based on the original forward function, which is incorrect. As a result, this PR also introduces an internal attribute `.traceable` to `nn.Module`, and we check this attribute to determine whether a Slapo customized module is traceable.
cc @chhzh123
=> [Primitive][fork_rng] Do not replace module

examples/bert/deepspeed_hf.py, examples/data_util.py, examples/gpt2/deepspeed_hf.py, examples/gpt_neo/deepspeed_hf.py, tests/end2end.py
This PR changes BERT's training script to load from the real wikipedia dataset. It refactors the `data_util.py` file in order to support different models and datasets.
=> [examples] Refactor dataloader to support BERT

slapo/model_schedule/gpt2.py, tests/test_shard.py
When sharding word embedding, we use forward pre-hook to mask inputs for different devices in a TP group. Accordingly, we have to mask the invalid output using the same mask in forward post-hook. Since the input mask generated in pre-hook cannot be saved, we currently re-generate the mask in post-hook. However, at this moment the input is already masked, so we cannot re-generate a mask using the same logic.
cc @chhzh123 @zarzen
=> [Bugfix] Shard embedding hooks

setup.py, slapo/version.py, update_version.py
I realized that I forgot to bump the version in `slapo/version.py` to `v0.0.2.dev0` in the last release. This results in some confusions, because when user install Slapo from source, they still see `v0.0.1.dev0`. This PR refactors the version updating logic to prevent this case from happening again in the future release.
1. Make `slapo/version.py` the only place to specify the current dev version.
2. Add a sanity check when building a wheel. Specifically, if it attempts to update the version from `v0.0.x.dev0` in version.py to `v0.0.y` where `y != x` , then errors out. This is used to make sure we bump the version in `version.py` before releasing a new stable version.
3. Align the version when installing with `setup.py`.
In short, with this PR we now have the following behaviors:
1. When …
=> [Version] Refactor version updating logic

slapo/primitives/replace.py, tests/test_replace.py
This PR add a new `.replace_all()` primitive for users to quickly replace all the submodules that satisfy certain type constraints with the new module.
cc @comaniac
=> [Primitive] Add .replace_all()

slapo/primitives/replace.py, slapo/schedule.py, tests/test_replace.py, tests/test_utils.py
This PR introduces a new API `.named_schedules` to traverse all the subschedules, similar to `.named_modules()` in PyTorch. This can avoid the mismatching between `nn.ModuleList` and the created schedule.
cc @comaniac
=> [API] Add .named_schedules()

slapo/primitives/replace.py, tests/test_replace.py
This PR fixes two issues:
1. Previous implementation leverages `.named_schedule()` to get all the subschedules, which is a generator that generates the subschedules on-the-fly. However, when the user replaced module accidentally includes the original module, it will get into a infinite loop. One practical example is to replace `nn.Linear` with an inherited module or a sequential module that contains a `nn.Linear` layer. To fix it, we need to get all the subschedules first, and then replace them one by one.
2. Add `**kwargs` to `.replace_all()`, enabling users to pass additional arguments to the module constructor.
cc @comaniac
=> [Primitive] Add kwargs to .replace_all()

slapo/schedule.py, tests/test_subgraph.py
This PR is an enhancement to #58. Although #58 adds support for tree-like subgraph matching, it makes the original QKV matching invalid. This is because the user of a graph node may not be the immediate successor of it, so we need to iteratively find its correct user. For the following case, `y` is not the user of `x` but is the immediate successor of `x`. When we do the pattern matching, we need to skip `y` but to match `z`.
```python
x = a + b
y = c + d (totally independent from x)
z = x + 1
m = p + q
n = m + 1
```
In general, subgraph isomorphism is an NP-complete problem, and the current implementation is a greedy algorithm that leverages the property of sequential representation of the computation graph, but it cannot guarantee all the patterns can be matched.
cc @comaniac
=> [Bugfix] Fix QKV matching

slapo/build.py, slapo/verify.py, tests/test_verify.py
This PR follows #87 to enhance the verification support in order to help programmers find bugs in distributed programs in advance. There are several changes:
1. Enhance the consolidation logic for HF models, so that users need not necessarily provide the `_init_weight` function but can still use PyTorch's method to initialize the model.
2. Add `eval_mode` in the argument of the verifier so users can determine whether they want to include `dropout` layers in the verification process.
3. Change the verification logic. First generate the results of the original model and immediately free it to reduce memory usage.
4. Add a test case to verify the TP sharding of the HF BERT model.
cc @comaniac @zarzen
=> [Verification] Enhanced verifier for end-to-end HF model testing

slapo/tracer.py, tests/test_trace.py
This PR enhances the HF tracer to let it trace at arbitrary levels. It is now able to trace the GPT attention module.
We customize the tracer function in order to fit our cases. Specifically, 
1. We need to maintain the original function arguments, so these several lines of code are not needed. https://github.com/huggingface/transformers/blob/v4.28.1/src/transformers/utils/fx.py#L1078-L1103
2. We need to make sure the name of function arguments are the same as the original module, so a modification to the argument naming is needed. https://github.com/awslabs/slapo/blob/v0.0.3/slapo/tracer.py#L409-L414
cc @zarzen @comaniac
=> [Trace] Enhance HuggingFace tracer to support tracing at arbitrary levels

slapo/tracer.py, tests/test_trace.py
This PR adds TorchDynamo as the backend tracer, providing more use cases when integrating with PyTorch 2.0.
Also, the legacy HF tracer is fixed to support tracing GPT attention modules.
cc @comaniac @zarzen @whbldhwj
=> [Tracer] Add TorchDynamo support

examples/gpt2/deepspeed_hf.py, slapo/framework_dialect/deepspeed/pipeline.py, slapo/pipeline.py, slapo/primitives/replace.py, slapo/schedule.py, slapo/utils/common.py, tests/test_pipeline_partition.py
This PR fixes the incorrect argument order in the pipeline module. See the following description. The previous implementation only fixes the argument order between pipeline stages, but does not handle the input mismatch.
```python
(input_ids, past_key_values, attention_mask, token_type_ids, position_ids, ...)
(input_ids, attention_mask, position_ids)
(input_ids, position_ids, attention_mask)
```
cc @comaniac @zarzen
=> [Pipeline] Fix incorrect argument order in the pipeline module

slapo/framework_dialect/deepspeed/engine.py, slapo/framework_dialect/deepspeed/pipeline.py
- Disable the `is_pipe_partition` and `is_grad_partition` in DeepSpeed PipelineEngine. By default these two vars are `True`, which leads to incorrect send receive buffer sizes. Slapo already handles partitioned inputs from stage to stage.
=> [Pipeline] [Bugfix] Make 3D compatible with dmlc/DeepSpeed

slapo/primitives/replace.py, slapo/schedule.py, tests/test_replace.py, tests/test_subgraph.py
This PR refactors the `.replace()` and `.find()` primitives to let them support more cases:
1. Based on the discussion in the PyTorch [issue](https://github.com/pytorch/pytorch/issues/53534), we can wrap an fx function inside the pattern function context using `exec`. Therefore, we do not need to manually parse the source code and wrap it in a module, allowing users to write more free-form patterns, e.g. directly calling global variables, using third-party library functions. To be more specific, the following pattern is not allowed before this PR. This PR also adds a complete test case to replace the scaled dot product function in the BERT attention module.
```python
def pattern(attn_scores):
return attn_scores / math.sqrt(  # non-builtin Python function
config.hidden_size // …
```
=> [Primitive] .find() & .replace() API enhancement
